# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
